# Symbolic links to be created


# [TARGET]                   [LINK_NAME]
# (relative to $PWD)         (relative to $HOME)

bash-config/bashrc           .bashrc
bash-config/bash_profile     .bash_profile

X11-config/bspwm             .config/bspwm
X11-config/sxhkd             .config/sxhkd
X11-config/xinitrc           .xinitrc
X11-config/Xresources        .Xresources

git-config/gitconfig         .gitconfig

vim-config/vimrc             .vimrc

