# Symbolic links to be created


# [TARGET]                   [LINK_NAME]
# (relative to $PWD)         (relative to $HOME)

bash-config/bashrc           .bashrc
bash-config/bash_profile     .bash_profile

X11-config/bspwm             .config/bspwm
X11-config/sxhkd             .config/sxhkd
X11-config/termite           .config/termite
X11-config/xinitrc           .xinitrc
X11-config/xserverrc         .xserverrc
X11-config/Xresources        .Xresources

git-config/gitconfig         .gitconfig

vim-config/vimrc             .vimrc
vim-config/vimrcs            .vim/vimrcs
vim-config/myUltiSnips       .vim/myUltiSnips

# tmux
other/tmux.conf              .tmux.conf
other/tmux.conf.local        .tmux.conf.local
# clang-format
other/clang-format           .clang-format
# Zathura
other/zathura                .config/zathura
# Configuration file for pycodestyle
other/pycodestyle            .config/pycodestyle
# Configuration file for vint (Vim script linter)
other/vintrc.yml             .vintrc.yml
# Typescript configuration
other/tsconfig.json          tsconfig.json
