# Symbolic links to be created


# [TARGET]                                [LINK_NAME]
# (relative to $PWD)                      (relative to $HOME)

bash-config/bashrc                        .bashrc
bash-config/bash_profile                  .bash_profile

git-config/gitconfig                      .gitconfig

vim-config/vimrc                          .vimrc
vim-config/vimrcs                         .vim/vimrcs
vim-config/myUltiSnips                    .vim/myUltiSnips

# tmux
other/tmux.conf                           .tmux.conf
other/tmux.conf.local                     .tmux.conf.local
