#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi







# Touchpad setting
TOUCHPAD="$(xinput list --name-only | grep 'Touchpad')"
xinput set-prop "$TOUCHPAD" 'libinput Tapping Enabled' 1
xinput set-prop "$TOUCHPAD" 'libinput Natural Scrolling Enabled' 1
xinput set-prop "$TOUCHPAD" 'libinput Horizontal Scroll Enabled' 0

export LC_CTYPE=zh_TW.UTF-8
export XMODIFIERS="@im=gcin"
export GTK_IM_MODULE="gcin"
export QT_IM_MODULE="gcin"

gcin &

exec bspwm
