#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# systemd

systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# Touchpad setting
TOUCHPAD="$(xinput list --name-only | grep 'Touchpad')"
xinput set-prop "$TOUCHPAD" 'libinput Tapping Enabled' 1
xinput set-prop "$TOUCHPAD" 'libinput Natural Scrolling Enabled' 1
xinput set-prop "$TOUCHPAD" 'libinput Horizontal Scroll Enabled' 0
xinput disable "$TOUCHPAD"
unclutter --timeout 0 &

# Sound setting
amixer set Master mute

# gcin
export LC_CTYPE=zh_TW.UTF-8
export XMODIFIERS="@im=gcin"
export GTK_IM_MODULE="gcin"
export QT_IM_MODULE="gcin"
gcin &

# clipmenu
export CM_MAX_CLIPS=8    # maximum number of clips to store
export CM_HISTLENGTH=8   # number of lines to show in dmenu
clipmenud &

# bspwm
chmod a+x ~/.config/bspwm/bspwmrc
exec bspwm
