#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=vim

alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -a'
alias grep='grep --color=auto'
alias vi='vim'

# Custom local settings
[[ -f ~/.bashrc_local ]] && . ~/.bashrc_local
